### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by luisherranz**
Trying to merge upstream changes.

### CODE REVIEW

**Comment by luisherranz** [comment]
@c4rl0sbr4v0 I'm having problems running the linters in my machine. As [you've done this in the past](https://github.com/woocommerce/woocommerce-blocks-hydration-experiments/pull/69), would you mind helping me out? Thanks!! 🙏

**Comment by luisherranz** [comment]
@c4rl0sbr4v0 wait, all the lint-related tasks passed. Then, I don't know why they were failing in my machine 🤷‍♂️

Anyway, no need to help then! Thanks anyway 😄

**Review by cbravobernal — APPROVED** [review]
Blind approval 😆

**Comment by luisherranz** [comment]
I may have broken something in the Cart Order Summary Coupon Form block. I'll check it out later.

**Pull request merged**
